services:
  - type: web
    name: MedJournee_Backend
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
